### ISSUE TITLE
Expense entry page

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Harvest#108]
Show the total for the quantity selected.
Also, for the quantity, maybe make the label Quantity (Per Acre) in this example:

![image](https://user-images.githubusercontent.com/469010/115609353-461f8200-a29c-11eb-80cf-3fccacfdaf2f.png)

**Comment by srkirkland** [comment]
Main problem here is i don't know if the person entering the expenses should be able to see total.  Another problem is that for truly "other" expenses that box is no longer quantity and will just be the total so we have to handle that.  Also the label is dynamic so that will require some coordination
